apiVersion: v1
kind: Secret
metadata:
  name: payment-credentials
type: Opaque
stringData:
  JWT_SIGNING_SECRET: "SuperSecretJwtTokenKeyForProductionOnly2026"
  SPEI_GATEWAY_KEY: "spei_live_prod_acc_77362819"
